// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef interface_h
#define interface_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Output.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Input.H>
#include <FL/Fl_Check_Button.H>

class UserInterface {
public:
  Fl_Double_Window* make_window();
  Fl_Box *titre;
  Fl_Box *taille_fichier;
  Fl_Output *fichier;
  Fl_Button *btn_browse_file;
  Fl_Output *chemin;
  Fl_Button *btn_browse_dir;
  Fl_Box *label_taille_division;
  Fl_Round_Button *check1;
  Fl_Choice *combo_taille;
  Fl_Round_Button *check2;
  Fl_Input *taille;
  Fl_Choice *combo_mesure;
  Fl_Check_Button *rassembler;
  Fl_Button *btn_split;
  Fl_Button *btn_quitter;
  Fl_Button *btn_about;
  Fl_Double_Window* make_about();
  Fl_Button *about_button;
};
#endif
