// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "interface.h"

Fl_Double_Window* UserInterface::make_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(310, 315, "Ultra Splitter 3.2");
    w = o;
    o->selection_color(FL_SELECTION_COLOR);
    o->user_data((void*)(this));
    o->align(FL_ALIGN_CENTER);
    o->when(FL_WHEN_CHANGED);
    { Fl_Box* o = titre = new Fl_Box(66, 16, 178, 30, "Ultra Splitter");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(1);
      o->labelsize(24);
      o->labelcolor(FL_DARK_BLUE);
    }
    { Fl_Box* o = taille_fichier = new Fl_Box(154, 55, 105, 15);
      o->labelsize(10);
      o->align(FL_ALIGN_BOTTOM_RIGHT|FL_ALIGN_INSIDE);
    }
    { Fl_Output* o = fichier = new Fl_Output(25, 71, 235, 23, "Fichier \340 Diviser:");
      o->color((Fl_Color)215);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_DARK_BLUE);
      o->textsize(12);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btn_browse_file = new Fl_Button(264, 71, 23, 23, "...");
      o->tooltip("Parcourir pour trouver le fichier... Racourcis: CTRL-O");
      o->box(FL_ROUND_UP_BOX);
      o->shortcut(0x4006f);
      o->labelfont(1);
      o->labelsize(11);
    }
    { Fl_Output* o = chemin = new Fl_Output(25, 111, 235, 23, "Chemin des divisions:");
      o->color((Fl_Color)215);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_DARK_BLUE);
      o->textsize(12);
      o->align(FL_ALIGN_TOP_LEFT);
    }
    { Fl_Button* o = btn_browse_dir = new Fl_Button(264, 111, 23, 23, "...");
      o->tooltip("Choisir le r\351pertoire... Racourcis: CTRL-d");
      o->box(FL_ROUND_UP_BOX);
      o->shortcut(0x40064);
      o->labelfont(1);
      o->labelsize(11);
    }
    { Fl_Box* o = new Fl_Box(25, 152, 260, 70);
      o->box(FL_ENGRAVED_BOX);
    }
    { Fl_Box* o = label_taille_division = new Fl_Box(31, 145, 154, 15, "Taille d\'une division:");
      o->box(FL_FLAT_BOX);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_DARK_BLUE);
      o->align(FL_ALIGN_TOP_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Round_Button* o = check1 = new Fl_Round_Button(32, 166, 122, 19, "Taille &pr\351""d\351""finie:");
      o->type(102);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->value(1);
      o->labelsize(12);
    }
    { Fl_Choice* o = combo_taille = new Fl_Choice(156, 166, 121, 21);
      o->box(FL_UP_BOX);
      o->down_box(FL_DOWN_BOX);
      o->color((Fl_Color)207);
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Round_Button* o = check2 = new Fl_Round_Button(32, 191, 122, 19, "Autre &Taille:");
      o->type(102);
      o->down_box(FL_ROUND_DOWN_BOX);
      o->labelsize(12);
    }
    { Fl_Input* o = taille = new Fl_Input(156, 191, 67, 21);
      o->type(1);
      o->color((Fl_Color)207);
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Choice* o = combo_mesure = new Fl_Choice(228, 191, 49, 21);
      o->down_box(FL_BORDER_BOX);
      o->color((Fl_Color)207);
      o->labelsize(12);
      o->textsize(12);
    }
    { Fl_Check_Button* o = rassembler = new Fl_Check_Button(25, 233, 260, 30, "Rassembler des divisions");
      o->tooltip("Choisir si l\'on doit diviser ou rassembler des fichiers...");
      o->box(FL_ENGRAVED_BOX);
      o->down_box(FL_DOWN_BOX);
      o->labelsize(12);
    }
    { Fl_Button* o = btn_split = new Fl_Button(102, 273, 103, 24, "&Diviser");
      o->box(FL_ROUND_UP_BOX);
      o->color(FL_DARK_BLUE);
      o->selection_color((Fl_Color)40);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor(FL_BACKGROUND2_COLOR);
    }
    { Fl_Button* o = btn_quitter = new Fl_Button(24, 273, 73, 24, "&Quitter");
      o->tooltip("Quitter le logiciel...");
      o->box(FL_ROUND_UP_BOX);
      o->labelsize(12);
    }
    { Fl_Button* o = btn_about = new Fl_Button(210, 273, 75, 24, "&A propos");
      o->tooltip("Quelques informations sur le programme...");
      o->box(FL_ROUND_UP_BOX);
      o->labelfont(2);
      o->labelsize(12);
    }
    o->end();
  }
  return w;
}

Fl_Double_Window* UserInterface::make_about() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(330, 420, "A propos du logiciel...");
    w = o;
    o->user_data((void*)(this));
    { Fl_Box* o = new Fl_Box(13, 112, 307, 146, "Ultra Splitter est un logiciel libre.\nVous avez le droit de l\'utiliser, le \
distribuer, \351tudier son code source et l\'am\351liorer selon les termes de \
la GNU General Public licence (version 2 ou ult\351rieure. Selon votre convena\
nce).\n\nLisez le fichier COPYING.txt ou COPYING-FR.txt pour plus d\'informati\
ons.");
      o->box(FL_SHADOW_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      o->labelsize(11);
      o->align(192|FL_ALIGN_INSIDE);
    }
    { Fl_Button* o = about_button = new Fl_Button(117, 383, 95, 23, "&Fermer");
      o->box(FL_ROUND_UP_BOX);
      o->labelsize(12);
    }
    { Fl_Box* o = new Fl_Box(96, 11, 138, 25, "UltraSplitter");
      o->color((Fl_Color)29);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelfont(1);
      o->labelsize(18);
      o->labelcolor(FL_DARK_BLUE);
    }
    { Fl_Box* o = new Fl_Box(30, 57, 269, 15, "Copyright (c) Asher256");
      o->color((Fl_Color)29);
      o->labelfont(1);
      o->labelsize(12);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(132, 35, 65, 15, "Version 3.2");
      o->labelfont(1);
      o->labelsize(10);
      o->labelcolor((Fl_Color)59);
    }
    { Fl_Box* o = new Fl_Box(13, 263, 307, 104, " Ce programme est la mise \340 jour du pr\351""c\351""dent Ultra Splitter fai\
t en QuickBasic. L\'ancienne version ne contenait pas d\'interface graphique e\
t ne marchait que sous DOS. Cette version marche sur deux syst\350mes d\'explo\
itations: Windows et GNU/Linux. ");
      o->box(FL_RSHADOW_BOX);
      o->color((Fl_Color)96);
      o->labelsize(11);
      o->labelcolor(FL_BACKGROUND2_COLOR);
      o->align(196|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(102, 74, 126, 13, "contact@asher256.com");
      o->color((Fl_Color)29);
      o->labelsize(10);
      o->labelcolor((Fl_Color)112);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = new Fl_Box(54, 89, 222, 13, "http://usplit.asher256.com");
      o->color((Fl_Color)29);
      o->labelfont(1);
      o->labelsize(12);
      o->labelcolor((Fl_Color)4);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    o->set_modal();
    o->end();
  }
  return w;
}
